In [1]:
import numpy as np
print(np.array([1, 2, 3]) + 5)

[6 7 8]

In [3]:
import pandas as pd

df = pd.read_csv('data/cafe_sales.csv')

display(df.head())

print("rows and columns: ", df.shape)
print("column: ", df.columns.tolist())

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2,4,Credit Card,Takeaway,09-08-23
1,TXN_4977031,Cake,4,3,12,Cash,In-store,05-16-23
2,TXN_4271903,Cookie,4,1,ERROR,Credit Card,In-store,07-19-23
3,TXN_7034554,Salad,2,5,10,UNKNOWN,UNKNOWN,04-27-23
4,TXN_3160411,Coffee,2,2,4,Digital Wallet,In-store,06-11-23

rows and columns:  (10000, 8)
column:  ['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent', 'Payment Method', 'Location', 'Transaction Date']

In [4]:
from src.processing import report_missing_values

display(report_missing_values(df))

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [5]:
"""df.info()"""

'df.info()'

In [6]:
from src.processing import replace_placeholders

print("Before:")
display(df.isna().sum())

cleaned_df = replace_placeholders(df)

print("After:")
display(cleaned_df.isna().sum())

Before:

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

After:

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [7]:
display(cleaned_df.head())

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2,4,Credit Card,Takeaway,09-08-23
1,TXN_4977031,Cake,4,3,12,Cash,In-store,05-16-23
2,TXN_4271903,Cookie,4,1,NaN,Credit Card,In-store,07-19-23
3,TXN_7034554,Salad,2,5,10,NaN,NaN,04-27-23
4,TXN_3160411,Coffee,2,2,4,Digital Wallet,In-store,06-11-23

In [8]:
from src.processing import convert_column_types

cleaned_df = convert_column_types(cleaned_df)

cleaned_df.info()
display(cleaned_df.head())

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9031 non-null   str
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    6822 non-null   str
 6   Location          6039 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(3), str(4)
memory usage: 625.1 KB

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [13]:
import numpy as np

total_spent = cleaned_df['Total Spent'].dropna().to_numpy(dtype=float)

print("Transactions with total spent:", total_spent.size)
print("Average amount spent:", round(np.mean(total_spent), 2))
print("Median amount spent:", round(np.median(total_spent), 2))
print("Smallest amount:", np.min(total_spent))
print("Largest amount:", np.max(total_spent))

Transactions with total spent: 9498
Average amount spent: 8.92
Median amount spent: 8.0
Smallest amount: 1.0
Largest amount: 25.0

In [9]:
from src.processing import report_missing_values

display(report_missing_values(cleaned_df))

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64